name: CI

on:
  push:
    branches:
      - devel
    tags:
      - '**'
  pull_request:

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Find Python version
        run: echo "PYTHON_VERSION=$(grep python_version Pipfile | cut -d= -f 2 | tr -d '\" ')" >> "$GITHUB_ENV"
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pipenv'
      - run: pip install pipenv
      - run: pipenv sync
      - run: pipenv run nikola build
      - name: Upload artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v4
        with:
          path: output

  deploy:
    needs: build
    if: github.event_name == 'push'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-24.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4